### ISSUE TITLE
[Bug] Ignoring values with didSet/willSet

### ISSUE THREAD

**Issue by brzzdev** [SwiftyLab/MetaCodable#10]
I think by trying to ignore computed variables, you've inadvertently ignored values with didSet and willSet

Since updating to a more recent version I now get the error
`Return from initializer without initializing all stored properties`
when my struct contains something like
```
var example: String {
    didSet {
        // do something
    }
}
```

**Comment by soumyamahunt** [comment]
I think the correct approach will be to check for only `get` accessors.

**Comment by soumyamahunt** [comment]
@brzzdev can you check if PR #11 is working for you.

**Comment by brzzdev** [comment]
It is indeed! The expanded macro looks exactly like I would expect too 😄
