### ISSUE TITLE
Unable to build in Xcode 16.0 — Getting strict concurrency build errors

### ISSUE THREAD

**Issue by hisaac** [SwiftyLab/MetaCodable#108]
- [x] I have read the [documentation](https://swiftpackageindex.com/SwiftyLab/MetaCodable/main/documentation/metacodable).
- [x] I have read the [limitations](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable/limitations).
- [x] I could not find my [issue](https://github.com/SwiftyLab/MetaCodable/issues).

**Describe the bug**

I'm getting build errors when I try to use MetaCodable in a Swift Package using Xcode 16:

![CleanShot 2024-10-16 at 18 48 10@2x](https://github.com/user-attachments/assets/70d0a71f-e291-4078-836b-7fd5ee6fc7c5)

Is there a recommended way to use this library without tripping these strict concurrency checks?

**To Reproduce**

1. Create a Swift Package manifest (Package.swift).
2. Include MetaCodable as a dependency, and add it as a dependency to one of the package's targets.
3. Try to build that target.
4. Observe build errors.

**Expected behavior**

The Swift Package should build with MetaCodable included.

**Screenshots**

**Environment (please complete the following information, remove ones not applicable):**

- OS: macOS
- Version: 15.0.1
- Xcode: 16.0.0
- Swift: 6.0, 5.9

**Additional context**

Some things I've tried to resolve the issue:

- Setting the `// swift-tools-version:` in the Package.swift file to 5.9.
- Adding `swiftLanguageVersions: [.v5]` to the Package definition.
- Importing MetaCodable using the `@preconcurrency` keyword (`@preconcurrency import MetaCodable`).

**Comment by soumyamahunt** [comment]
Thanks for the detailed report @hisaac. Are you seeing just those two errors you have mentioned or are you seeing more errors?

I am able to build with XCode 16 and my CI and Swift Package Index CI is able to build without any issues. Can you help with following details to resolve this:
- Sample project that can reproduce error.
- `swift-syntax` version you are using (Can you upgrade to latest version and see if that resolves your issue).

**Comment by hisaac** [comment]
> `swift-syntax` version you are using (Can you upgrade to latest version and see if that resolves your issue).

This was the issue! For whatever reason, it was trying to use an older version of `swift-syntax` (don't remember specifically what version, but it was `510.x`). When I refreshed the cache, it updated to `600.0.1` and is working as expected now.

Thank you for the suggestion. Any idea why it could've cloned an older version originally?

**Comment by soumyamahunt** [comment]
> Thank you for the suggestion. Any idea why it could've cloned an older version originally?

Can't say for sure, but older version of `MetaCodable` was using `510.x` version of swift-syntax, may be you recently upgraded `MetaCodable`?

**Comment by hisaac** [comment]
Ah I figured it out. One of the other dependencies I was using also depends on `swift-syntax`, but requires a lower version, so it was resolving to that lower version.
