### ISSUE TITLE
[Bug] doesn't seem to work with Mac Catalyst

### ISSUE THREAD

**Issue by robaho** [SwiftyLab/MetaCodable#110]
OSX 13.7
XCode 15.2
Swift 5.9
MetaCodable 1.3.0 or 1.4.0

It fails building building for Mac Catalyst with

PhaseScriptExecution Parse\ source\ file\ \"SeaDocument\"\ in\ module\ \"Seahorse\" /Users/robertengels/Seahorse/DerivedData/Seahorse/Build/Intermediates.noindex/Seahorse.build/Debug-maccatalyst/Seahorse.build/Script-2BA047B22CC82055001235E1.sh (in target 'Seahorse' from project 'Seahorse')
    cd /Users/robertengels/Seahorse
    /bin/sh -c /Users/robertengels/Seahorse/DerivedData/Seahorse/Build/Intermediates.noindex/Seahorse.build/Debug-maccatalyst/Seahorse.build/Script-2BA047B22CC82055001235E1.sh

sandbox-exec: execvp() of '//Users/robertengels/Seahorse/DerivedData/Seahorse/Build/Products/Debug/ProtocolGen' failed: No such file or directory

The problem seems to be that it is building in Debug-maccatalyst, but it is trying to run the ProtocolGen binary in the Debug directory - checking the filesystem it isn't there - it is in the Debug-maccatalyst product directory.

Any ideas?

**Comment by robaho** [comment]
If I manually copy the ProtoGen binary into the directory it seems to work, but obviously this isn't right, as cleaning the build directory will remove it again.

**Comment by soumyamahunt** [comment]
@robaho can you provide a minimal sample app reproducing the issue?

**Comment by soumyamahunt** [comment]
@robaho this seems like a known Xcode issue: https://github.com/swiftlang/swift-package-manager/issues/6619, hence closing this. An alternative will be to use this library CocoaPods for now.

**Comment by robaho** [comment]
Thanks for the update @soumyamahunt Is there anyway to work around it? Like I said, if I copy the binary into the directory it works - maybe the the script running could change the path, or put those binaries in outside known directory?

**Comment by soumyamahunt** [comment]
@robaho for SPM plugins I don't have control over the path, hence not possible. The proper way to get this working is giving feedback to Apple to fix this bug.
