### ISSUE TITLE
[Feature Request] CodedAt support parent path

### ISSUE THREAD

**Issue by BlackCatHehe** [SwiftyLab/MetaCodable#119]
Thank you for the great codable macro support package
- [x] I have read the [documentation](https://swiftpackageindex.com/SwiftyLab/MetaCodable/main/documentation/metacodable).
- [x] I have read the [limitations](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable/limitations).
- [ ] I could not find my [request](https://github.com/SwiftyLab/MetaCodable/issues).
- [ ] I have tried implementing this request with [`HelperCoder`](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable/helpercoder).

Recently, I encountered a scenario while using the package. I read the documentation but still couldn't figure out how to implement it.
I have two types of JSON, which are:
```swift
let json1: [String: Any]  = [
    "id": "1",
    "code": 111,
    "data": [
        "url": "bing",
        "name": "hai"
    ]
]

let json2 = [
    "id": "2",
    "code": 222,
    "data": [
        "id": "bing",
        "action": "hai"
    ]
] as [String : Any]
```
If I place the code field inside data, using codedAt and codedAs works fine. However, the code is currently designed to be at the same level as data field.
I tried using DynamicCodable and protocol methods to create different structs, but in my model, only the structure within the data level is different, and I don't want my entire model to change accordingly.

My expectations should be like the following:
```swift
@Codable
**@CodedAt("../code)"**
@CodedAs<Int>
enum DData {
    @CodedAs(111)
    case a(url: String, name: String)
    @CodedAs(222)
    case b(id: String, action: String)
}

@Codable
struct Model {
    let id: String
    let code: Int
    
    let data: DData
}
```
Are there any existing solutions?

**Comment by soumyamahunt** [comment]
@BlackCatHehe sounds like you are data is structured similar to [adjacent tagging](https://swiftpackageindex.com/swiftylab/metacodable/main/tutorials/metacodable/enum#Create-Codable-enums-with-adjacent-tag), have you looked into if this will resolve your requirement?

**Comment by BlackCatHehe** [comment]
> It should not be possible. In my JSON, besides the "code" and "data" fields, there can be many other fields that I need to use. What I need is to use "data" as a separate enum.
I used GPT for translation, so please excuse any inaccuracies.

**Comment by BlackCatHehe** [comment]
@soumyamahunt  It should not be possible. In my JSON, besides the "code" and "data" fields, there can be many other fields that I need to use. What I need is to use "data" as a separate enum.
I used GPT for translation, so please excuse any inaccuracies.

**Comment by soumyamahunt** [comment]
@BlackCatHehe you can try combining [`CodedAt`](https://swiftpackageindex.com/swiftylab/metacodable/v1.4.0/documentation/metacodable/codedat(_:)) without any arguments as demonstrated [here](https://swiftpackageindex.com/swiftylab/metacodable/v1.4.0/tutorials/metacodable/essential#Share-common-Codable-fields) to have something like this:
```swift
@Codable
struct Model {
    let id: String
    let code: Int
    @CodedAt
    let data: DData

    @Codable
    @CodedAt("code")
    @ContentAt("data")
    @CodedAs<Int>
    enum DData {
        @CodedAs(111)
        case a(url: String, name: String)
        @CodedAs(222)
        case b(id: String, action: String)
    }
}
```

**Comment by BlackCatHehe** [comment]
It works!, thank you😀
