### ISSUE TITLE
Class implementation

### ISSUE THREAD

**Issue by itzaks** [SwiftyLab/MetaCodable#19]
Hi! 

Great macro. Any chance to make it work for classes?

**Comment by soumyamahunt** [comment]
Thanks @itzaks.

The major challenge of making it work with classes is knowing whether the `super` class conforms to `Codable` already or not. Currently there is no way for macros to know that, however after [this](https://github.com/apple/swift-evolution/blob/main/proposals/0407-member-macro-conformances.md) pitch implemented and available it will be possible to do so.

**Comment by itzaks** [comment]
I see, thanks! 🙂

**Comment by MartinLau7** [comment]
I noticed that this pitch was already implemented in 5.9.2

**Comment by soumyamahunt** [comment]
> I noticed that this pitch was already implemented in 5.9.2

Thanks for noticing this, didn't think they will add this feature to the new fix release. Now classes can be supported with some change.

**Comment by soumyamahunt** [comment]
@MartinLau7 swift-syntax hasn't released the update in protocol requirement, it is present in main branch but hasn't been released yet.

This needs to be released as well for `MetaCodable` to support this feature.

**Comment by MartinLau7** [comment]
@soumyamahunt Thank you for your reply. I can assist with testing once a new version is released.

**Comment by soumyamahunt** [comment]
Thanks @MartinLau7, the changes are ready in #48, branch `class-support`. You can comment out following lines in `Package.swift` to use a custom swift-syntax branch that has the required changes:

https://github.com/SwiftyLab/MetaCodable/blob/c1a4284d42bf1dcb98af3bfcf73d719267e4bce8/Package.swift#L49
https://github.com/SwiftyLab/MetaCodable/blob/c1a4284d42bf1dcb98af3bfcf73d719267e4bce8/Package.swift#L63

Let me know if you face any issues.

**Comment by MartinLau7** [comment]
@soumyamahunt
 I apologize for not being able to respond in time earlier.  I was ill and had to take some time off.
I ran the tests locally as you instructed.  Are the tests in the class-support branch currently available?  When I run the unit tests, the Class section fails.

<img width="1139" alt="image" src="https://github.com/SwiftyLab/MetaCodable/assets/5416852/c1779245-d222-428f-99b2-6b2a6c0c0c30">

**Comment by soumyamahunt** [comment]
> @soumyamahunt I apologize for not being able to respond in time earlier. I was ill and had to take some time off.

No issues, hope you are feeling better now.

> I ran the tests locally as you instructed. Are the tests in the class-support branch currently available? When I run the unit tests, the Class section fails.

I meant playing with the feature as in writing some class models using the library. Unit test support for this macro feature hasn't been added in swift-syntax as well. Also, you don't need to run tests manually, CI takes care of that.

**Comment by MartinLau7** [comment]
Thank you for your explanation. I have already tried the demo locally and it is working fine. Thank you for your help.

**Comment by itzaks** [comment]
Amazing. Thanks for all your work! Looking forward to test it.
