### ISSUE TITLE
[Bug] @Codable fails in structs with static members.

### ISSUE THREAD

**Issue by Midbin** [SwiftyLab/MetaCodable#26]
In my testing `@Codable` fails for structs which include static members:

``` swift
@Codable
struct Test {
  static var test = "test"
}
```
Fails with `Failed to receive result from plugin (from macro 'Codable')`.

It also fails in all other common permutations (with normal members etc.)

A working workaround for now is to declare these static members in an extension.

**Comment by soumyamahunt** [comment]
@Midbin do you want to create PR for this?

**Comment by Midbin** [comment]
I created #37
