### ISSUE TITLE
Support for customizing/removing nested key for enums with associated values?

### ISSUE THREAD

**Issue by Sajjon** [SwiftyLab/MetaCodable#30]
Hey! Great lib! Does it already support this use case?

```swift
struct StateHolder: Codable {
	let state: State
	enum State: Codable {
		case on(On)
		case off(Off)
		struct On: Codable {
			let onOnlyProperty: String
		}
		struct Off: Codable {
			let offOnlyProperty: String
		}
	}
}
```

when I JSON encode `StateHolder(state: .on(.init(onOnlyProperty: "On!")))` Swift produces:
```json
{
	"state" : {
		"on" : {
			"_0" : {
				"onOnlyProperty": "On!"
			}
		}
	}
}
```

Or using `.off` respectively: 

```json
{
	"state" : {
		"off" : {
			"_0" : {
				"offOnlyProperty": "Off!"
			}
		}
	}
}
```

Which is... well I think that was strange design decision [by SE-0295](https://github.com/apple/swift-evolution/blob/main/proposals/0295-codable-synthesis-for-enums-with-associated-values.md).

I always manually change this to:

```json
{
	"state" : {
		"discriminator": "on",
		"on" : {
			"onOnlyProperty": "On!"
		}
	}
}
```
Is this support by the lib? Or something you would consider adding?

**Comment by soumyamahunt** [comment]
Thanks @Sajjon, unfortunately generating `Codable` implementation for enums is not supported yet.

I would definitely consider adding support for enum. The major challenge is finding a generalized way of implementation that will work for all the users (which I am still figuring out). Let me know if you have anything in mind.

**Comment by soumyamahunt** [comment]
@Sajjon I have created #31 for discussing enum support, feel free to go through it and suggest any changes you would like with Enum types support

**Comment by soumyamahunt** [comment]
@Sajjon enum support has been [released](https://github.com/SwiftyLab/MetaCodable/releases/tag/v1.2.0).
