### ISSUE TITLE
Does IgnoreCoding support properties with didSet?

### ISSUE THREAD

**Issue by MartinLau7** [SwiftyLab/MetaCodable#53]
<img width="782" alt="image" src="https://github.com/SwiftyLab/MetaCodable/assets/5416852/ce84eac2-bc40-4bd3-abe4-95774d12572d">

When using MetaCodable with IgnoreCoding to ignore properties, it doesn't support properties configured with didSet. What should I do?

**Comment by soumyamahunt** [comment]
This looks like a bug, for now you can use [`@IgnoreCodingInitialized()`](https://swiftpackageindex.com/swiftylab/metacodable/v1.2.0/documentation/metacodable/ignorecodinginitialized()) instead.
