### ISSUE TITLE
SwiftData class: Method does not override any method from its superclass

### ISSUE THREAD

**Issue by ashleydw** [SwiftyLab/MetaCodable#56]
If a SwiftData model annotation is added to a class, the build will fail with "Method does not override any method from its superclass".

It can be reproduced using a clean SwiftData project, adding the SPM package from 1.2.1, and the following class:

```swift
import Foundation
import SwiftData
import MetaCodable
import HelperCoders

protocol MyProtocol {
    
}

@Codable
@Model
final class Item : MyProtocol {
    @CodedAt("timestamp")
    var timestamp: Date? = nil
    
    init() { }
}
```

Expanding the macro actually shows it *doesn't* add the `super.*` calls:

<img width="910" alt="image" src="https://github.com/SwiftyLab/MetaCodable/assets/844437/c4ca93af-b520-4fc0-9fea-801406a27cdd">

I have however managed to produce one expansion with the error:

![image](https://github.com/SwiftyLab/MetaCodable/assets/844437/453357f8-4759-4efc-9b49-4e4bfee8ea7f)

**Comment by ashleydw** [comment]
Here's a repo: https://github.com/ashleydw/metacodable-min-ex/blob/main/test/Item.swift

If you build you should get the same error on Item.swift. Commenting out `@Codable` and `CodedAt` should build successfully and run.

**Comment by soumyamahunt** [comment]
Thanks @ashleydw for providing sample, I can reproduce your issue. The issue doesn't seem to be combining `@Codable` with SwiftData class, in fact the project builds successfully if you comment out following lines:

https://github.com/ashleydw/metacodable-min-ex/blob/c0bd383995ca3c12938f704b79429e2c9c7b0c9b/test/ContentView.swift#L6
https://github.com/ashleydw/metacodable-min-ex/blob/c0bd383995ca3c12938f704b79429e2c9c7b0c9b/test/ContentView.swift#L11-L18
https://github.com/ashleydw/metacodable-min-ex/blob/c0bd383995ca3c12938f704b79429e2c9c7b0c9b/test/ContentView.swift#L50
https://github.com/ashleydw/metacodable-min-ex/blob/c0bd383995ca3c12938f704b79429e2c9c7b0c9b/test/ContentView.swift#L58

Seems like with these line present Swift is not providing protocol conformance data to `@Codable`. It would be better if you create a discussion on [Swift forum](https://forums.swift.org/) or [Apple developer forum](https://developer.apple.com/forums/) as the issue doesn't seem to be `MetaCodable` related.

**Comment by Willian-Zhang** [comment]
Same issue here, 

problem magically disappear when  `#Preview` section commented out of some random View (no `@
State`, no `@Query` no anything), other `#Preview` that contains a `@Query` not affected by this

**Comment by Willian-Zhang** [comment]
And it happens to me when I move `@Bindable var someEnvObject = someEnvObject` in scope of a body of a View that takes and EnvroementObject (check below for doc), to 1 `ZStack` level inside...

``` swift
// @Bindable var someEnvObject = someEnvObject <- from here
ZStack {
  @Bindable var someEnvObject = someEnvObject <- to here
  // some other code using `someEnvObject`
}
```


<img width="990" alt="image" src="https://github.com/SwiftyLab/MetaCodable/assets/5165840/75d8a7f1-062a-421c-a087-6261cb700b21">
(Apple doc)[https://developer.apple.com/documentation/swiftui/bindable]

**Comment by soumyamahunt** [comment]
@ashleydw @Willian-Zhang has any of you created discussion on [Swift forum](https://forums.swift.org/) or [Apple developer forum](https://developer.apple.com/forums/)?

I am afraid this issue is not related to `MetaCodanle`, taking the discussion to Swift team/Apple is the only solution to this.

**Comment by Willian-Zhang** [comment]
> @ashleydw @Willian-Zhang has any of you created discussion on [Swift forum](https://forums.swift.org/) or [Apple developer forum](https://developer.apple.com/forums/)?
> 
> I am afraid this issue is not related to `MetaCodanle`, taking the discussion to Swift team/Apple is the only solution to this.

I haven't, I wasn't able to identify where to problem lies to. 
The only thing I can be sure about is that it happens with this use case and reporting this exact error from Codable generated code.

**Comment by soumyamahunt** [comment]
> > @ashleydw @Willian-Zhang has any of you created discussion on [Swift forum](https://forums.swift.org/) or [Apple developer forum](https://developer.apple.com/forums/)?
> > I am afraid this issue is not related to `MetaCodanle`, taking the discussion to Swift team/Apple is the only solution to this.
> 
> I haven't, I wasn't able to identify where the problem lies to. The only thing I can be sure about is that it happens with this use case and reporting this exact error from `@Codable` generated code.

Simple overview of the class implementation generation by `@Codable`:
```
-> Does Class conform to `Decodable`/`Encodable`? (passed from Swift compiler to `MetaCodable`)
    -> Yes
        -> Are `Decodable`/`Encodable` conformance implemented i.e. `init(from:)`/`encode(to:)` method implementation exist?
            -> Yes
                -> Skip generating implementation
            -> No
                 -> Assume that super class conforms to `Decodable`/`Encodable` and provide generated implementation.
    -> No
        -> No super class conforms to `Decodable`/`Encodable` and provide generated implementation.
```

The strange thing here is without those lines the Swift compiler invokes the following flow:
```
-> Does Class conform to `Decodable`/`Encodable`? (passed from Swift compiler to `MetaCodable`)
    -> No
        -> No super class conforms to `Decodable`/`Encodable` and provide generated implementation.
```

and with those lines present the Swift compiler invokes the following flow:
```
-> Does Class conform to `Decodable`/`Encodable`? (passed from Swift compiler to `MetaCodable`)
    -> Yes
        -> Are `Decodable`/`Encodable` conformance implemented i.e. `init(from:)`/`encode(to:)` method implementation exist?
            -> No
                 -> Assume that super class conforms to `Decodable`/`Encodable` and provide generated implementation.
```

which is a strange behaviour from compiler, as of why compiler provides wrong data in some cases, only Swift compiler team can answer.

**Comment by Willian-Zhang** [comment]
@soumyamahunt  great insight! 
@soumyamahunt @ashleydw Are you available to fire a bug report or discussion as you said to apple by any chance?
I don't think I'm qualified enough for this as I'm new to SwiftLang let alone I have 0 insight on how swift macro works.

If not, do you think there is way to go around with this problem? I am very interested in this cross usage on SwiftData+MetaCodable usage as it would vastly simplify my code in a project that I started recently. (Actually I'm current on a track giving up on `#Preview` capability just to have this working)

**Comment by soumyamahunt** [comment]
@ashleydw @Willian-Zhang new macro [`Inherits`](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable/inherits(decodable:encodable:)) has been added (only in `main` branch, not released yet) to workaround the issue until this is fixed from compiler.

**Comment by Willian-Zhang** [comment]
having [Inherits](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable/inherits(decodable:encodable:)) tested, I can confirm this solved my problem perfectly.

**Comment by rursache** [comment]
not sure what i'm doing wrong. using the `main` branch and this code:

```swift
@Codable
@Model
@Inherits(decodable: false, encodable: false)
final class TestModel: Codable, Identifiable {
  var id: Int = 0
  var url: String = ""
  var name: String = ""
  
  init(id: Int, url: String, name: String) {
    self.id = id
    self.url = url
    self.name = name
  }
}
```

Fails with
`Redundant conformance of 'EpisodeModel' to protocol 'Decodable'`
`Redundant conformance of 'EpisodeModel' to protocol 'Encodable'`

any idea @soumyamahunt ? thanks!

**Comment by soumyamahunt** [comment]
@rursache you have to remove the manual `Codable` conformance you are adding, due to this addition compiler is also generating `Codable` implementation which is conflicting with this library's generated implementation.

**Comment by ashleydw** [comment]
@soumyamahunt I can confirm it works in my project, thanks!

**Comment by bfalcinelli** [comment]
Please, release a new version with this fix

**Comment by soumyamahunt** [comment]
@bfalcinelli currently the proper fix can be done from compiler end, as the issue arises due to compiler providing wrong data to 'MetaCodable'.

The current work around has been released: https://github.com/SwiftyLab/MetaCodable/releases/tag/v1.4.0
