### ISSUE TITLE
Cocoapods installation does not work

### ISSUE THREAD

**Issue by manelmateos** [SwiftyLab/MetaCodable#61]
Hi,

when I add pod 'MetaCodable' to my project, I get this error: 
**_env: /my_project_path/Pods/MetaCodableMacro/Utils/macro_plugin_build.sh: No such file or directory_**

If I see 'Pods/MetaCodableMacro' the Utils directory doesn't exist.

**Comment by soumyamahunt** [comment]
Cocoapods support isn't released yet, the pod you are seeing is an experimental release as part of my CocoaPods support exploration.

The next tagged release will have CocoaPods support. You can either use the main branch or wait for the next release.

**Comment by soumyamahunt** [comment]
@manelmateos CocoaPods support has been [released](https://github.com/SwiftyLab/MetaCodable/releases/tag/v1.3.0)

**Comment by Mioke** [comment]
I create a new demo project and only `pod 'MetaCodable', '1.3.0` in this project's `Podfile`, and it built failed. error is :
```
error: 'metacodablemacro': Source files for target PluginCore should be located under 'Sources/PluginCore', or a custom sources path can be set with the 'path' property in Package.swift
```

**Comment by soumyamahunt** [comment]
@Mioke can you provide the demo project?

**Comment by Mioke** [comment]
> @Mioke can you provide the demo project?

https://github.com/Mioke/resources/blob/master/CMSTest.zip
@soumyamahunt can try this.

**Comment by Mioke** [comment]
Still the same, confirmed deleting the `Pods` folder and then installing again.

**Comment by crazypoo** [comment]
same same
