### ISSUE TITLE
[Help wanted] How can it test the macro test?

### ISSUE THREAD

**Issue by HIIgor** [SwiftyLab/MetaCodable#86]
![image](https://github.com/SwiftyLab/MetaCodable/assets/13389736/c62411f7-5eb8-4a58-9790-12e9fecd4d8c)

SWIFT_SYNTAX_EXTENSION_MACRO_FIXED is always false

**Comment by soumyamahunt** [comment]
`SWIFT_SYNTAX_EXTENSION_MACRO_FIXED` is enabled based on environment variable, the logic for it can be found in `Package.swift` file:
https://github.com/SwiftyLab/MetaCodable/blob/83ea43ad539713e25480a81675c12829ce5c2567/Package.swift#L106

I normally use VSCode for development which allows defining custom environment variables per workspace, which is defined here:
https://github.com/SwiftyLab/MetaCodable/blob/83ea43ad539713e25480a81675c12829ce5c2567/.vscode/settings.json#L17

For XCode as far as I know there is no nicer way to manage this configuration, other than defining environment variable from command line. May be you can try disabling the condition in `Package.swift` which will allow you to run the tests.

**Comment by HIIgor** [comment]
There doesn't seem to be a relatively simple way to run the test, running the test is mainly to see how it work internally. 
I would try some other way to workaround, Thank you all the same.

**Comment by soumyamahunt** [comment]
@HIIgor you can use the same workaround suggested [here](https://github.com/SwiftyLab/MetaCodable/issues/28#issuecomment-1792609898) to enable testing.

**Comment by soumyamahunt** [comment]
@HIIgor closing this since it seems your query is resolved.
