### ISSUE TITLE
[Feature Request] Create helper types for specialized data decoding/encoding

### ISSUE THREAD

**Issue by soumyamahunt** [SwiftyLab/MetaCodable#9]
- [x] Create type that only decodes valid data and ignores invalid data for collections, instead of typical way of failing entire decoding when encountering invalid data.
- [ ] Create type that decodes a basic data type (i.e `Bool`, `Int`, `String`) from any basic data type (i.e `Bool`, `Int`, `String`).
- [ ] Create type that provides various approaches to `Date` decoding/encoding.
- [ ] Create type that provides various approaches to `Data` decoding/encoding.
- [ ] Create type that provides various approaches to non-confirming floats decoding/encoding.
- [ ] Create type that can accept two different instances of `ExternalHelperCoder`, decodes and encodes with different instances.

**Comment by murad1981** [comment]
That would be a cool feature that reduces so much boilerplate code for simple tasks.
