### ISSUE TITLE
[Bug] Build failed when nesting classes.

### ISSUE THREAD

**Issue by hstdt** [SwiftyLab/MetaCodable#94]
- [X] I have read the [documentation](https://swiftpackageindex.com/SwiftyLab/MetaCodable/main/documentation/metacodable).

**Describe the bug**
When nesting classes, `required init(from decoder: any Decoder) throws` and `func encode(to encoder: any Encoder) throws` will generate incorrect codes.

**To Reproduce**
``` swift
@Codable
class SomeClassA {
    var b: SomeClassB?
    var c: SomeClassC?
}

@Codable
class SomeClassB {
}

@Codable
class SomeClassC {

}
```

**Expected behavior**
Just build.

**Screenshots**
![CleanShot 2024-07-30 at 17 23 29](https://github.com/user-attachments/assets/ae82e32a-5212-4a71-a0a2-0a86ea212c9a)

**Environment (please complete the following information, remove ones not applicable):**
 - OS: macOS 14/15
 - Version: all
 - Xcode 15/16
 - Swift 5.9

**Additional context**
Nothing.

**Comment by hstdt** [comment]
Update: reproduct with less code:

```
class SomeClassA {
    var b: SomeClassB?
}

@Codable
class SomeClassB {
}
```

![CleanShot 2024-07-30 at 17 33 13](https://github.com/user-attachments/assets/f3f0f828-d909-49e3-a1d1-89c050e4d103)

**Comment by hstdt** [comment]
PS: I tried same code in tests, code runs as expect.

![CleanShot 2024-07-30 at 17 49 18](https://github.com/user-attachments/assets/1912b9db-0c6f-41f3-a2fa-f8ebc9407d77)

**Comment by hstdt** [comment]
PPS:

```swift
class SomeClass: Codable {
    var b: SomeClassB?
}

@Codable
class SomeClassB: SomeClass {
}
```

![CleanShot 2024-07-30 at 19 19 25](https://github.com/user-attachments/assets/fde6491f-7285-4a5d-88b7-7c5bdc2319b4)

while in tests:

![CleanShot 2024-07-30 at 19 41 19](https://github.com/user-attachments/assets/c1077f8b-279e-4b35-b960-03169d9ba60a)

**Comment by soumyamahunt** [comment]
@hstdt when I copy the snippet provided by you to a separate project I don't see this issue.

Your issue is most likely same as #56, workaround suggested there should work also.
