### ISSUE TITLE
[Feature Request] Support Swift 6.0

### ISSUE THREAD

**Issue by ltns35** [SwiftyLab/MetaCodable#98]
- [x] I have read the [documentation](https://swiftpackageindex.com/SwiftyLab/MetaCodable/main/documentation/metacodable).

**Describe the bug**
The library is unusable when compiling the project using XCode 16 and Swift 6.0

**To Reproduce**
Try to compile the project using XCode 16 and Swift 6.0

**Expected behavior**
The project should be able to compile without errors.

**Environment (please complete the following information, remove ones not applicable):**
 - OS: [macOS]
 - Version [e.g. 15.0]
 - Xcode [e.g. 16.0]
 - Swift [e.g. 6.0]

**Comment by soumyamahunt** [comment]
Xcode 16 is not stable yet. Can you specify what error are you getting?

**Comment by philipbel** [comment]
> Xcode 16 is not stable yet. Can you specify what error are you getting?

Xcode has never been really stable 🤣

Xcode 16 is officially [released](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes), though.

**Comment by soumyamahunt** [comment]
> > Xcode 16 is not stable yet. Can you specify what error are you getting?
> 
> Xcode has never been really stable 🤣
> 
> Xcode 16 is officially [released](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes), though.

I am aware that it is released, the comment was made when it was still on beta.
Also, I am not sure what support is needed as both my CI and Swift Package Index CI indicate library works on Swift 6.

**Comment by soumyamahunt** [comment]
@ltns35 I am able to use this library Xcode 16 stable version just fine, since you haven't provided any sample project that can reproduce this issue, I am assuming you want this library migrate to Swift 6 language mode. I am converting this to a 
 feature request.
